### ISSUE TITLE
edit and review the draft (version 0.0)

### ISSUE THREAD

**Issue by litanda** [litanda/GPGrid_paper#5]
Hi Guy, 

I have written up a draft for the GP paper. Can you please have a look at it and give me some general feedback? 

For the introduction and conclusion sections, I have written some texts based on my understanding of the field. Can you add some more? If you are short of time, just send me an outline or several keywords.  

For the language issues, please feel free to edit the tex files. I trust native speakers. 

Cheers, 

Tanda

**Comment by grd349** [comment]
Thanks Tanda - great job.  I will have a look next week! :)

**Comment by litanda** [comment]
The draft is restructured following Guy's comments. Version 0.1 is uploaded.
